version: '3'
services:
  sftp:
    image: atmoz/sftp
    ports:
      - 22:22
    volumes:
      - ./public-key:/home/gmsca/.ssh/keys
      - ./data:/home/gmsca/Distribution/GMS
    environment:
      - SFTP_USERS=gmsca::::Distribution/GMS