package ca.gms
package parsers

import utils.Utils._

import org.slf4j.LoggerFactory
import scala.collection.mutable

class HealthELIGParser {

  def GetHeaderActions(): mutable.Map[String, String => Any] = mutable.Map[String, String=>Any](
    "record_type" -> ((line: String) => ExtractField(line, Array(0,2))),
    "file_type" -> ((line: String) => ExtractField(line, Array(2,4))),
    "payor_ansi_number" -> ((line: String) => ExtractField(line, Array(4,10), toInt)),
    "source_name" -> ((line: String) => ExtractField(line, Array(10,30))),
    "creation_date" -> ((line: String) => ExtractField(line, Array(30,38), FormatDateString)),
    "creation_time" -> ((line: String) => ExtractField(line, Array(38,42), FormatTimeString)),
    "transmittal_sequence_number" -> ((line: String) => ExtractField(line, Array(42,45), toInt)),
    "format_version" -> ((line: String) => ExtractField(line, Array(45,47))),
    "load_type" -> ((line: String) => ExtractField(line, Array(47,51))),
    "comment" -> ((line: String) => ExtractField(line, Array(51,59))),
    "tpa_indicator" -> ((line: String) => ExtractField(line, Array(59,62)))
  )

  def GetClientActions(): mutable.Map[String, String => Any] = mutable.Map[String, String=>Any](
    "record_type" -> ((line: String) => ExtractField(line, Array(0,2))),
    "carrier_id" -> ((line: String) => ExtractField(line, Array(2,4))),
    "group_number" -> ((line: String) => ExtractField(line, Array(4,14))),
    "sas" -> ((line: String) => ExtractField(line, Array(14,23))),
    "client_id" -> ((line: String) => ExtractField(line, Array(23,38))),
    "general_processing_mode" -> ((line: String) => ExtractField(line, Array(38,39))),
    "alternate_identification" -> ((line: String) => ExtractField(line, Array(39,55))),
    "client_language_flag_code" -> ((line: String) => ExtractField(line, Array(55,56))),
    "client_province_code" -> ((line: String) => ExtractField(line, Array(56,58))),
    "eft_account_number" -> ((line: String) => ExtractField(line, Array(58,70))),
    "eft_route_code" -> ((line: String) => ExtractField(line, Array(70,79))),
    "eft_effective_date" -> ((line: String) => ExtractField(line, Array(79,87), FormatDateString)),
    "eft_termination_date" -> ((line: String) => ExtractField(line, Array(87,95), FormatDateString)),
    "lookup_override_code" -> ((line: String) => ExtractField(line, Array(95,96))),
    "employment_enrolment_date" -> ((line: String) => ExtractField(line, Array(96,104), FormatDateString)),
    // pharmacy section
    "pharmacy_processing_mode" -> ((line: String) => ExtractField(line, Array(154,155))),
    "carrier_pharmacy_field" -> ((line: String) => ExtractField(line, Array(155,165))),
    "drug_effective_date" -> ((line: String) => ExtractField(line, Array(165,173), FormatDateString)),
    "drug_termination_date" -> ((line: String) => ExtractField(line, Array(173,181), FormatDateString)),
    "plan_number" -> ((line: String) => ExtractField(line, Array(181,186))),
    "client_benefit_override_code" -> ((line: String) => ExtractField(line, Array(186,191))),
    "dur_flag" -> ((line: String) => ExtractField(line, Array(191,192))),
    "provincial_cob_rule_number" -> ((line: String) => ExtractField(line, Array(192,193))),
    "ramq_override_flag" -> ((line: String) => ExtractField(line, Array(193,194))),
    "cutback_override_indicator" -> ((line: String) => ExtractField(line, Array(194,195))),
    "mandatory_generic_override_indicator" -> ((line: String) => ExtractField(line, Array(195,196))),
    "therapeutic_reference_number_override" -> ((line: String) => ExtractField(line, Array(196,200))),
    "max_dependant_age" -> ((line: String) => ExtractField(line, Array(200,202))),
    "max_student_age" -> ((line: String) => ExtractField(line, Array(202,204))),
    "general_code" -> ((line: String) => ExtractField(line, Array(204,205))),
    "suspend_flag" -> ((line: String) => ExtractField(line, Array(205,206))),
    "coverage_code" -> ((line: String) => ExtractField(line, Array(206,208))),
    "cob_status_code" -> ((line: String) => ExtractField(line, Array(208,209))),
    // dental section
    "dental_processing_mode" -> ((line: String) => ExtractField(line, Array(259,260))),
    "carrier_dental_field" -> ((line: String) => ExtractField(line, Array(260,270))),
    "dental_record_effective_date" -> ((line: String) => ExtractField(line, Array(270,278), FormatDateString)),
    "dental_record_expiry_date" -> ((line: String) => ExtractField(line, Array(278,286), FormatDateString)),
    "plan_number" -> ((line: String) => ExtractField(line, Array(286,291))),
    "client_benefit_override_code" -> ((line: String) => ExtractField(line, Array(291,296))),
    "private_cob_rule_number" -> ((line: String) => ExtractField(line, Array(296,298))),
    "max_dependant_age" -> ((line: String) => ExtractField(line, Array(298,300))),
    "max_student_age" -> ((line: String) => ExtractField(line, Array(300,302))),
    "general_code" -> ((line: String) => ExtractField(line, Array(302,303))),
    "suspend_flag" -> ((line: String) => ExtractField(line, Array(303,304))),
    "coverage_code" -> ((line: String) => ExtractField(line, Array(304,306))),
    "cob_status_code" -> ((line: String) => ExtractField(line, Array(306,307))),
    "cost_plus" -> ((line: String) => ExtractField(line, Array(307,308))),
    "edi_threshold_amount" -> ((line: String) => ExtractField(line, Array(308,315))),
  )

  def GetPatientActions(): mutable.Map[String, String => Any] = mutable.Map[String, String=>Any](
    "record_type" -> ((line: String) => ExtractField(line, Array(0,2))),
    "carrier_id" -> ((line: String) => ExtractField(line, Array(2,4))),
    "group_number" -> ((line: String) => ExtractField(line, Array(4,14))),
    "sas" -> ((line: String) => ExtractField(line, Array(14,23))),
    "client_id" -> ((line: String) => ExtractField(line, Array(23,38))),
    "current_patient_code" -> ((line: String) => ExtractField(line, Array(38,41))),
    "general_processing_mode" -> ((line: String) => ExtractField(line, Array(41,42))),
    "relationship_code" -> ((line: String) => ExtractField(line, Array(42,43))),
    "full_patient_last_name" -> ((line: String) => ExtractField(line, Array(43,73))),
    "full_patient_first_name_initial" -> ((line: String) => ExtractField(line, Array(73,103))),
    "patient_middle_initial" -> ((line: String) => ExtractField(line, Array(103,104))),
    "patient_date_of_birth" -> ((line: String) => ExtractField(line, Array(104,112))),
    "patient_sex" -> ((line: String) => ExtractField(line, Array(112,113))),
    "new_patient_code" -> ((line: String) => ExtractField(line, Array(113,116))),
    "dental_enrolment_date" -> ((line: String) => ExtractField(line, Array(116,124), FormatDateString)),
    // pharmacy section
    "pharmacy_processing_mode" -> ((line: String) => ExtractField(line, Array(182,183))),
    "drug_effective_date" -> ((line: String) => ExtractField(line, Array(183,191), FormatDateString)),
    "drug_termination_date" -> ((line: String) => ExtractField(line, Array(191,199), FormatDateString)),
    "plan_number" -> ((line: String) => ExtractField(line, Array(199,204))),
    "patient_benefit_override_code" -> ((line: String) => ExtractField(line, Array(204,209))),
    "cob_status" -> ((line: String) => ExtractField(line, Array(209,210))),
    "suspend_flag" -> ((line: String) => ExtractField(line, Array(210,211))),
    "exception_flag" -> ((line: String) => ExtractField(line, Array(211,212))),
    "enrollment_date" -> ((line: String) => ExtractField(line, Array(212,220), FormatDateString)),
    // dental section
    "dental_processing_mode" -> ((line: String) => ExtractField(line, Array(261,262))),
    "dental_record_effective_date" -> ((line: String) => ExtractField(line, Array(262,270), FormatDateString)),
    "dental_record_expiry_date" -> ((line: String) => ExtractField(line, Array(270,278), FormatDateString)),
    "plan_number" -> ((line: String) => ExtractField(line, Array(278,283))),
    "patient_benefit_override_code" -> ((line: String) => ExtractField(line, Array(283,288))),
    "cob_status" -> ((line: String) => ExtractField(line, Array(288,289))),
    "suspend_flag" -> ((line: String) => ExtractField(line, Array(289,290))),
    "late_entrant_indicator" -> ((line: String) => ExtractField(line, Array(290,291))),
    "cost_plus" -> ((line: String) => ExtractField(line, Array(291,292))),
    "private_cob_rule_code" -> ((line: String) => ExtractField(line, Array(292,294))),
    "edi_threshold_amount" -> ((line: String) => ExtractField(line, Array(294,301))),
  )

  def GetEHCClientActions(): mutable.Map[String, String => Any] = mutable.Map[String, String=>Any](
    "record_type" -> ((line: String) => ExtractField(line, Array(0,2))),
    "carrier_id" -> ((line: String) => ExtractField(line, Array(2,4))),
    "group_number" -> ((line: String) => ExtractField(line, Array(4,14))),
    "sas" -> ((line: String) => ExtractField(line, Array(14,23))),
    "client_id" -> ((line: String) => ExtractField(line, Array(23,38))),
    "general_processing_mode" -> ((line: String) => ExtractField(line, Array(38,39))),
    "alternate_identification" -> ((line: String) => ExtractField(line, Array(39,55))),
    "client_language_flag_code" -> ((line: String) => ExtractField(line, Array(55,56))),
    "client_province_code" -> ((line: String) => ExtractField(line, Array(56,58))),
    "eft_account_number" -> ((line: String) => ExtractField(line, Array(58,70))),
    "eft_route_code" -> ((line: String) => ExtractField(line, Array(70,79))),
    "eft_effective_date" -> ((line: String) => ExtractField(line, Array(79,87), FormatDateString)),
    "eft_termination_date" -> ((line: String) => ExtractField(line, Array(87,95), FormatDateString)),
    "lookup_override_code" -> ((line: String) => ExtractField(line, Array(95,96))),
    "employment_enrolment_date" -> ((line: String) => ExtractField(line, Array(96,104), FormatDateString)),
    // ehc section
    "ehc_processing_mode" -> ((line: String) => ExtractField(line, Array(154,155))),
    "carrier_ehc_field" -> ((line: String) => ExtractField(line, Array(155,165))),
    "ehc_record_effective_date" -> ((line: String) => ExtractField(line, Array(165,173), FormatDateString)),
    "ehc_record_expiry_date" -> ((line: String) => ExtractField(line, Array(173,181), FormatDateString)),
    "plan_number" -> ((line: String) => ExtractField(line, Array(181,186))),
    "client_benefit_override_code" -> ((line: String) => ExtractField(line, Array(186,191))),
    "private_cob_rule_number" -> ((line: String) => ExtractField(line, Array(191,193))),
    "max_dependant_age" -> ((line: String) => ExtractField(line, Array(193,195))),
    "max_student_age" -> ((line: String) => ExtractField(line, Array(195,197))),
    "general_code" -> ((line: String) => ExtractField(line, Array(197,198))),
    "suspend_flag" -> ((line: String) => ExtractField(line, Array(198,199))),
    "coverage_code" -> ((line: String) => ExtractField(line, Array(199,201))),
    "cob_status_code" -> ((line: String) => ExtractField(line, Array(201,202))),
    "cost_plus" -> ((line: String) => ExtractField(line, Array(202,203))),
    "edi_threshold_amount" -> ((line: String) => ExtractField(line, Array(203,210)))
  )

  def GetEHCPatientActions(): mutable.Map[String, String => Any] = mutable.Map[String, String=>Any](
    "record_type" -> ((line: String) => ExtractField(line, Array(0,2))),
    "carrier_id" -> ((line: String) => ExtractField(line, Array(2,4))),
    "group_number" -> ((line: String) => ExtractField(line, Array(4,14))),
    "sas" -> ((line: String) => ExtractField(line, Array(14,23))),
    "client_id" -> ((line: String) => ExtractField(line, Array(23,38))),
    "current_patient_code" -> ((line: String) => ExtractField(line, Array(38,41))),
    "general_processing_mode" -> ((line: String) => ExtractField(line, Array(41,42))),
    "relationship_code" -> ((line: String) => ExtractField(line, Array(42,43))),
    "full_patient_last_name" -> ((line: String) => ExtractField(line, Array(43,73))),
    "full_patient_first_name_initial" -> ((line: String) => ExtractField(line, Array(73,103))),
    "patient_middle_initial" -> ((line: String) => ExtractField(line, Array(103,104))),
    "patient_date_of_birth" -> ((line: String) => ExtractField(line, Array(104,112), FormatDateString)),
    "patient_sex" -> ((line: String) => ExtractField(line, Array(112,113))),
    "new_patient_code" -> ((line: String) => ExtractField(line, Array(113,116))),
    "ehc_enrolment_date" -> ((line: String) => ExtractField(line, Array(116,124), FormatDateString)),
    // ehc section
    "ehc_processing_mode" -> ((line: String) => ExtractField(line, Array(182,183))),
    "ehc_record_effective_date" -> ((line: String) => ExtractField(line, Array(183,191), FormatDateString)),
    "ehc_record_expiry_date" -> ((line: String) => ExtractField(line, Array(191,199), FormatDateString)),
    "plan_number" -> ((line: String) => ExtractField(line, Array(199,204))),
    "patient_benefit_override_code" -> ((line: String) => ExtractField(line, Array(204,209))),
    "cob_status" -> ((line: String) => ExtractField(line, Array(209,210))),
    "suspend_flag" -> ((line: String) => ExtractField(line, Array(210,211))),
    "late_entrant_indicator" -> ((line: String) => ExtractField(line, Array(211,212))),
    "cost_plus" -> ((line: String) => ExtractField(line, Array(212,213))),
    "private_cob_rule_code" -> ((line: String) => ExtractField(line, Array(213,215))),
    "edi_threshold_amount" -> ((line: String) => ExtractField(line, Array(215,222)))
  )

  def GetEHCPatientAccumulatorActions(): mutable.Map[String, String => Any] = mutable.Map[String, String=>Any](
    "record_type" -> ((line: String) => ExtractField(line, Array(0,2))),
    "carrier_id" -> ((line: String) => ExtractField(line, Array(2,4))),
    "group_number" -> ((line: String) => ExtractField(line, Array(4,14))),
    "client_id" -> ((line: String) => ExtractField(line, Array(23,38))),
    "patient_code" -> ((line: String) => ExtractField(line, Array(38,41))),
    "effective_date" -> ((line: String) => ExtractField(line, Array(41,49), FormatDateString)),
    "accumulator_instruction" -> ((line: String) => ExtractField(line, Array(49,50))),
    "accumulator_type" -> ((line: String) => ExtractField(line, Array(50,52))),
    "accumulator_amount" -> ((line: String) => ExtractField(line, Array(52,59))),
    "category_code" -> ((line: String) => ExtractField(line, Array(59,61))),
    "accumulator_id" -> ((line: String) => ExtractField(line, Array(61,66))),
    "provider_number" -> ((line: String) => ExtractField(line, Array(66,75))),
    "trans_reference_number" -> ((line: String) => ExtractField(line, Array(75,89))),
    "procedure_paid_line_number" -> ((line: String) => ExtractField(line, Array(89,91))),
    "tooth_code" -> ((line: String) => ExtractField(line, Array(91,93))),
    "benefit_year_rollover_date" -> ((line: String) => ExtractField(line, Array(93,101), FormatDateString))
  )

  def GetPatientExceptionActions(): mutable.Map[String, String => Any] = mutable.Map[String, String=>Any](
    "record_type" -> ((line: String) => ExtractField(line, Array(0,2))),
    "carrier_id" -> ((line: String) => ExtractField(line, Array(2,4))),
    "group_number" -> ((line: String) => ExtractField(line, Array(4,14))),
    "sas" -> ((line: String) => ExtractField(line, Array(14,23))),
    "client_id" -> ((line: String) => ExtractField(line, Array(23,38))),
    "patient_code" -> ((line: String) => ExtractField(line, Array(38,41))),
    // pharmacy section
    "pharmacy_processing_mode" -> ((line: String) => ExtractField(line, Array(41,42))),
    "effective_date" -> ((line: String) => ExtractField(line, Array(42,50), FormatDateString)),
    "expiry_date" -> ((line: String) => ExtractField(line, Array(50,58), FormatDateString)),
    "drug_level" -> ((line: String) => ExtractField(line, Array(58,60))),
    "din" -> ((line: String) => ExtractField(line, Array(60,68), toInt)),
    "ramq_exception_code" -> ((line: String) => ExtractField(line, Array(68,72))),
    "gp_indicator" -> ((line: String) => ExtractField(line, Array(74,75))),
    "eclipse_code" -> ((line: String) => ExtractField(line, Array(75,77))),
    "therapeutic_class" -> ((line: String) => ExtractField(line, Array(77,83))),
    "seniors_flag" -> ((line: String) => ExtractField(line, Array(83,84))),
    "provincial_schedule_code" -> ((line: String) => ExtractField(line, Array(84,86))),
    "fed_sched_code" -> ((line: String) => ExtractField(line, Array(86,87))),
    "include_exclude_flag" -> ((line: String) => ExtractField(line, Array(87,88))),
    "exception_days_supply_reg" -> ((line: String) => ExtractField(line, Array(88,92))),
    "exception_days_supply_maint" -> ((line: String) => ExtractField(line, Array(92,96))),
    "except_override_code" -> ((line: String) => ExtractField(line, Array(96,101))),
    "accum_id" -> ((line: String) => ExtractField(line, Array(97,106))),
    "aqpp_code" -> ((line: String) => ExtractField(line, Array(106,109))),
    "cutback_override_indicator" -> ((line: String) => ExtractField(line, Array(114,115))),
    "mandatory_generic_override_indicator" -> ((line: String) => ExtractField(line, Array(115,116))),
    "therapeutic_reference_number_override" -> ((line: String) => ExtractField(line, Array(116,120))),
    "ramq_flag" -> ((line: String) => ExtractField(line, Array(120,121))),
    "disease_code" -> ((line: String) => ExtractField(line, Array(121,127))),
    // dental section (NOT USED)
    "dental_processing_mode" -> ((line: String) => ExtractField(line, Array(219,220))),
    "effective_date" -> ((line: String) => ExtractField(line, Array(220,228), FormatDateString)),
    "expiry_date" -> ((line: String) => ExtractField(line, Array(228,236), FormatDateString)),
    "proc_code" -> ((line: String) => ExtractField(line, Array(236,241))),
    "proc_code_source" -> ((line: String) => ExtractField(line, Array(241,245))),
    "lab_limit" -> ((line: String) => ExtractField(line, Array(245,251))),
    "expense_limit" -> ((line: String) => ExtractField(line, Array(251,257))),
    "category_code" -> ((line: String) => ExtractField(line, Array(257,259))),
    "freq_id_1" -> ((line: String) => ExtractField(line, Array(259,264))),
    "freq_id_2" -> ((line: String) => ExtractField(line, Array(264,269))),
    "freq_id_3" -> ((line: String) => ExtractField(line, Array(269,274))),
    "freq_id_4" -> ((line: String) => ExtractField(line, Array(274,279))),
    "material_intervention" -> ((line: String) => ExtractField(line, Array(279,281))),
    "include_exclude" -> ((line: String) => ExtractField(line, Array(281,282)))
  )

  def GetClientAddressActions(): mutable.Map[String, String => Any] = mutable.Map[String, String=>Any](
    "record_type" -> ((line: String) => ExtractField(line, Array(0,2))),
    "carrier_id" -> ((line: String) => ExtractField(line, Array(2,4))),
    "group_number" -> ((line: String) => ExtractField(line, Array(4,14))),
    "client_id" -> ((line: String) => ExtractField(line, Array(14,29))),
    "client_last_name" -> ((line: String) => ExtractField(line, Array(29,59))),
    "client_first_name" -> ((line: String) => ExtractField(line, Array(59,89))),
    "address_1" -> ((line: String) => ExtractField(line, Array(89,124))),
    "address_2" -> ((line: String) => ExtractField(line, Array(124,159))),
    "city" -> ((line: String) => ExtractField(line, Array(159,194))),
    "province" -> ((line: String) => ExtractField(line, Array(194,196))),
    "country" -> ((line: String) => ExtractField(line, Array(196,211))),
    "postal_code" -> ((line: String) => ExtractField(line, Array(211,217)))
  )

  def GetFileTotalsActions(): mutable.Map[String, String => Any] = mutable.Map[String, String=>Any](
    "record_type" -> ((line: String) => ExtractField(line, Array(0,2))),
    "file_type" -> ((line: String) => ExtractField(line, Array(2,4))),
    "payor_ansi_number" -> ((line: String) => ExtractField(line, Array(4,10), toInt)),
    "source_name" -> ((line: String) => ExtractField(line, Array(10,30))),
    "creation_date" -> ((line: String) => ExtractField(line, Array(30,38), FormatDateString)),
    "creation_time" -> ((line: String) => ExtractField(line, Array(38,42), FormatTimeString)),
    "record_count" -> ((line: String) => ExtractField(line, Array(42,50), toInt))
  )

}
