namespace GMS.ESC.FileParser.Models.ESC.Claims.Pharmacy
{
    public class ClaimRecord
    {
        public string RecordType { get; set; }
        public string VCSAssignedClaimReferenceNumber { get; set; }
        public string PharmacyTraceNumber { get; set; }
        public string DateClaimReceivedatESICanada { get; set; }
        public string DateProcessedAdjudicated { get; set; }
        public string ClaimStatus { get; set; }
        public string CommunicationsFlag { get; set; }
        public string ClientLanguageFlag { get; set; }
        public string PharmacyNumber { get; set; }
        public string PrescriptionNumber { get; set; }
        public string CurrentRxNumber { get; set; }
        public string DateOfService { get; set; }
        public string DINNumber_GPNumber { get; set; }
        public string DrugDescriptionEnglish { get; set; }
        public string DrugDescriptionFrench { get; set; }
        public string NewRefillCodeCPhAV2 { get; set; }
        public string MajorCompoundIngredient { get; set; }
        public string MetricQuantity { get; set; }
        public string DaysSupply { get; set; }
        public string ClientLastName { get; set; }
        public string ClientFirstName { get; set; }
        public string PatientLastName { get; set; }
        public string PatientFirstName { get; set; }
        public string PatientDateOfBirth { get; set; }
        public string SexOfPatient { get; set; }
        public string CustomerIDMajorAccountID { get; set; }
        public string GSAS { get; set; }
        public string ClientID { get; set; }
        public string PatientCode { get; set; }
        public string PatientRelationshipCode { get; set; }
        public string ProductSelectionCode { get; set; }
        public string SubmittedIngredientCost { get; set; }
        public string SubmittedCostUpCharge { get; set; }
        public string SubmittedProvincialTax { get; set; }
        public string SubmittedGST { get; set; }
        public string SubmittedProfessionalFee { get; set; }
        public string SubmittedGenericIncentive { get; set; }
        public string SubmittedSpecialServicesFee { get; set; }
        public string SubmittedCompoundingFee { get; set; }
        public string SubmittedCopay { get; set; }
        public string SubmittedCoinsurance { get; set; }
        public string SubmittedTotalAmountClaimed { get; set; }
        public string PayableIngredientCost { get; set; }
        public string PayableCostUpCharge { get; set; }
        public string PayableProvincialSalesTax { get; set; }
        public string PayableGSTTax { get; set; }
        public string PayableProfessionalFee { get; set; }
        public string PayableGenericIncentive { get; set; }
        public string PayableSpecialServicesFee { get; set; }
        public string PayableCompoundingFee { get; set; }
        public string PayableCopayAmount { get; set; }
        public string PayableCoinsurance { get; set; }
        public string PayableTotalAmount { get; set; }
        public string AmountTowardCostPlus { get; set; }
        public string AmountTowardAnnualDeductibleFamily { get; set; }
        public string AmountTowardAnnualDeductibleIndividualFamily { get; set; }
        public string AmountTowardAnnualDeductibleSingle { get; set; }
        public string AnnualDeductibleAmountSatisfiedFamily { get; set; }
        public string AnnualDeductibleAmountSatisfiedIndividualFamily { get; set; }
        public string AnnualDeductibleAmountSatisfiedSingle { get; set; }
        public string TestIndicator { get; set; }
        public string ErrorCodes { get; set; }
        public string CostBasis { get; set; }
        public string UnitPrice { get; set; }
        public string MaximumAllowableCost { get; set; }
        public string CostDifference { get; set; }
        public string TherapeuticClass { get; set; }
        public string FederalSchedule { get; set; }
        public string ProvincialSchedule { get; set; }
        public string DosageForm { get; set; }
        public string RouteOfAdministration { get; set; }
        public string SubmissionMethodCode { get; set; }
        public string PayeeCode { get; set; }
        public string PaymentMethod { get; set; }
        public string AuthorizationCode { get; set; }
        public string AuthorizationNumber { get; set; }
        public string EFTNumber { get; set; }
        public string DeductibleSatisfiedFlag { get; set; }
        public string NextRolloverDate { get; set; }
        public string PaymentStatus { get; set; }
        public string OriginalClaimReferenceNumber { get; set; }
        public string OriginalClaimTraceNumber { get; set; }
        public string ClientLocation { get; set; }
        public string ReimbursementFlag { get; set; }
        public string PrescriberNumber { get; set; }
        public string ProviderCode { get; set; }
        public string ProviderZone { get; set; }
        public string RefillsAuthorizedCPhAV3 { get; set; }
        public string DINProductName { get; set; }
        public string RefillRepeatAuthorizations { get; set; }
        public string ProvincialHealthCareID { get; set; }
        public string UnlistedCompound { get; set; }
        public string InterventionCodes { get; set; }
        public string PreviouslyPaid { get; set; }
        public string PharmacistID { get; set; }
        public string CPhAVersionNumber { get; set; }
        public string ESIEclipseCode { get; set; }
        public string AQPPCode { get; set; }
        public string Filler1 { get; set; }
        public string OriginalRxNumberCPhAV3 { get; set; }
        public string CurrentRxNumberCPhAV3 { get; set; }
        public string NewRefillCodeCPhAV3 { get; set; }
        public string MetricQuantityClaimedCPhAV3 { get; set; }
        public string MetricQuantityPaidCPhAV3 { get; set; }
        public string MedicalReasonReference { get; set; }
        public string MedicalCondition { get; set; }
        public string ProviderSoftwareID { get; set; }
        public string POSDeviceID { get; set; }
        public string PrescriberIDReference { get; set; }
        public string CPhAResponseCodes { get; set; }
        public string Dosage { get; set; }
        public string FormularyDrugIndicator { get; set; }
        public string AttachmentCode { get; set; }
        public string DiseaseCode { get; set; }
        public string COBRuleNumber { get; set; }
        public string GeneralCode { get; set; }
        public string GenProdIndicator { get; set; }
        public string PrescriberID { get; set; }
        public string PrescriberReferenceCode { get; set; }
        public string DeductPaid { get; set; }
        public string AccumID { get; set; }
        public string Deferred { get; set; }
        public string AlternateIdentification { get; set; }
        public string LineOfBusiness { get; set; }
        public string Filler2 { get; set; }
    }
}
